# ============================================================
# Redis Layer 로컬 개발 환경 설정
# ============================================================
# 활성화: spring.profiles.active=local
# ============================================================

spring:
  data:
    redis:
      host: localhost
      port: 6379
      # password: (로컬은 비밀번호 없음)
      database: 0

      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms
          time-between-eviction-runs: 30000ms

        shutdown-timeout: 200ms

redisson:
  single-server-config:
    address: "redis://localhost:6379"
    database: 0

    # Connection Pool (로컬: 작게)
    connection-pool-size: 8
    connection-minimum-idle-size: 2
    idle-connection-timeout: 10000
    connect-timeout: 3000
    timeout: 3000

    # Retry Settings
    retry-attempts: 3
    retry-interval: 1500
