# ============================================================
# Persistence Layer 로컬 개발 환경 설정
# ============================================================
# 활성화: spring.profiles.active=local
# ============================================================

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:setof-commerce}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}

    hikari:
      # Pool Size (로컬: 작게)
      maximum-pool-size: 5
      minimum-idle: 2

      # Timeout
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000

      # Leak Detection (로컬: 비활성화)
      leak-detection-threshold: 0

      pool-name: HikariPool-Local

      # MySQL 최적화
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  flyway:
    # ⚠️ 로컬에서도 clean 비활성화 (안전)
    clean-disabled: true

logging:
  level:
    com.ryuqq: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
