# ============================================================
# Persistence Layer 운영 환경 설정
# ============================================================
# 활성화: spring.profiles.active=prod
# ⚠️ 모든 민감 정보는 환경 변수로 관리
# ============================================================

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=true&requireSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      # Pool Size (운영: CPU 기반)
      # 공식: connections = (core_count * 2) + effective_spindle_count
      maximum-pool-size: 20
      minimum-idle: 10

      # Timeout
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

      # Leak Detection (운영: 활성화)
      leak-detection-threshold: 60000

      pool-name: HikariPool-Prod

      # Connection Health Check
      connection-init-sql: SELECT 1

      # MySQL 최적화 (운영)
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  flyway:
    # ⚠️ 운영에서 clean 절대 금지
    clean-disabled: true

logging:
  level:
    com.ryuqq: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
