# ===============================================
# REST API Adapter Configuration
# ===============================================
# REST API 어댑터 모듈 전용 설정
# Bootstrap 모듈에서 import하여 사용
#
# @author ryuqq
# @since 1.0.0
# ===============================================

# ===============================================
# REST API Configuration
# ===============================================
rest-api:
  # Rate Limiting
  rate-limit:
    enabled: false
    requests-per-second: 100
    burst-capacity: 200

# ===============================================
# Security Configuration
# ===============================================
security:
  # JWT 설정 (프로덕션에서 반드시 변경)
  jwt:
    secret: ${JWT_SECRET:setof-commerce-jwt-secret-key-must-be-changed-in-production-environment}
    access-token-expiration: 3600  # 1 hour (seconds)
    refresh-token-expiration: 604800  # 7 days (seconds)

  # Cookie 설정
  cookie:
    domain: ${COOKIE_DOMAIN:localhost}
    secure: ${COOKIE_SECURE:false}  # 프로덕션에서는 true
    same-site: lax  # csrf 보호를 위해 lax 또는 strict

  # 공개 엔드포인트 (인증 불필요)
  # method가 없으면 모든 HTTP 메서드 허용
  public-endpoints:
    # 회원 관련
    - method: POST
      pattern: /api/v1/members
    - method: POST
      pattern: /api/v1/members/password/reset
    # 인증 관련
    - method: POST
      pattern: /api/v1/auth/login
    - method: POST
      pattern: /api/v1/auth/refresh
    # OAuth2 관련 (모든 메서드)
    - pattern: /oauth2/**
    - pattern: /login/oauth2/**
    # Swagger/OpenAPI
    - pattern: /swagger-ui/**
    - pattern: /v3/api-docs/**
    # Actuator (헬스체크)
    - pattern: /actuator/**
    # Health Check
    - pattern: /api/v1/health

  # CORS 설정
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    exposed-headers:
      - Authorization
      - Set-Cookie
      - X-Request-Id
    allow-credentials: true

# ===============================================
# OAuth2 Configuration (Spring Security)
# ===============================================
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:your-kakao-client-id}
            client-secret: ${KAKAO_CLIENT_SECRET:your-kakao-client-secret}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - account_email
              - phone_number
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# ===============================================
# API Documentation (Springdoc OpenAPI)
# ===============================================
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

  packages-to-scan:
    - com.ryuqq.setof.api

  default-consumes-media-type: application/json
  default-produces-media-type: application/json